import { Inter } from "next/font/google";
import NavBar from "../Navbar/NavBar";
import Footer from "../Footer/Footer";
import styles from "./Layout.module.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children, global }) {
  return (
    <div className={inter.className}>
      <>
        <NavBar />
        <main className={styles.container}>
          <div className={styles.contentWrapper}>{children}</div>
        </main>
        <Footer global={global} />
      </>
    </div>
  );
}
