name: CI - Build Test

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: deps backend
        run: |
          cd backend
          bun install

      - name: set frontend env
        run: |
          echo "APP_KEYS=${{ secrets.APP_KEYS }}" > backend/.env
          echo "API_TOKEN_SALT=${{ secrets.API_TOKEN_SALT }}" >> backend/.env
          echo "ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }}" >> backend/.env
          echo "TRANSFER_TOKEN_SALT=${{ secrets.TRANSFER_TOKEN_SALT }}" >> backend/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> backend/.env

      - name: set backend env
        run: |
          echo "NEXT_PUBLIC_STRAPI_URL_PUBLIC=http://127.0.0.1:1337" > frontend/.env
          echo "STRAPI_URL_LOCAL=http://127.0.0.1:1337" >> frontend/.env
          echo "MY_TISCHTENNIS_LINK=${{ secrets.MY_TISCHTENNIS_LINK }}" >> frontend/.env
          echo "MY_TISCHTENNIS_ALL_GAMES=${{ secrets.MY_TISCHTENNIS_ALL_GAMES }}" >> frontend/.env

      - name: deps frontend
        run: |
          cd frontend
          bun install

      - name: deps root
        run: bun install

      - name: import strapi data
        run: |
          cd backend
          bun run ci:import-strapi-data

      - name: build backend
        run: |
          cd backend
          bun run build

      - name: run backend and build frontend
        run: bun run ci
